[build]
  publish = "docs/.vitepress/dist"
  command = "yarn docs:build"
[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "18.12.1"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional"
